[package]
name = "comonoid"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
description = "Comonoid trait"
documentation = "http://srijs.github.io/rust-comonoid/comonoid"
repository = "https://github.com/srijs/rust-comonoid"
license = "MIT"
